connect_scholars/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('general_user.urls',namespace="general_user")),
    path('',include('user_info.urls')),
    path('',include('logged_user.urls')),
    path('',include('admin_panel.urls')),

]

general_user/urls.py
from django.urls import path
from general_user import views
app_name='general_user'
urlpatterns=[
    
    path('',views.home_logout,name='home'),
    
    path('home/',views.home,name='general_user-home'),
    #path('home/',views.home_logout,name='home_logout'),
    
    
    path('search/',views.search,name='general_user-search'),
    
    path('search_sorted/',views.search_sort,name='general_user-search_sort'), 
    path('pdf/<int:pdf_id>',views.pdf,name='pdf'),
    path('author_pdf/<int:pdf_id>',views.pdf_from_authors,name='pdf_from_author'),
    path('author/<int:author_id>',views.author_description,name='author'),
    

]

user_info/urls.py
from django.urls import path,include
from user_info import views

app_name='user_info'
urlpatterns = [
    path('login/',views.login,name='Login'),
    path('register/',views.register,name='Register'),

]

general_user/models.py
from django.db import models

# Create your models here.

general_user/views.py
from django.shortcuts import render,HttpResponse
from django.db import connection, connections
from django.shortcuts import redirect, render,HttpResponse
from django.db import connection, connections
from django.shortcuts import reverse
import os

# Create your views here.

def home_logout(request):
    
    if 'loggedIn' in request.session:
       del request.session['loggedIn']
       

 
    papers=connections['scholars_db'].cursor().execute("select distinct T1.id as paper_id,T1.DOI,T1.TITLE,T1.published_year,T1.CITATION,NAME,abstract,publisher,url.id as url_id from paper T1 join  (select * from AUTHOROF) T2 on (T1.id=T2.paper_id) left outer join JOURNAL on (T1.journal_id = journal.journal_id) left outer join url on(T1.id=url.id) order by CITATION desc fetch first 3 rows only;")
       
    papers_recommended=[]
    if 'loggedIn' in request.session: 
       papers_recommended=dictfetchall(connections['scholars_db'].cursor().execute("select * from (select * from PAPER T1 join(select domain,max(CITATION) as max_cite from paper where DOMAIN in (select NAME from domain where id in (select DOMAIN_ID from EXPERTISE where AUTHOR_ID = '"+ str(request.session['user_id'])   +"')) group by DOMAIN) T2 on (T1.DOMAIN=T2.DOMAIN and T1.CITATION=T2.max_cite)) T1 join (select * from JOURNAL) T2 on (T1.JOURNAL_ID=T2.JOURNAL_ID);"))
      
    #ids=connections['scholars_db'].cursor().execute("select paper.id as paper_id from paper join authorof on (paper.id=authorof.author_id) left outer join JOURNAL on (paper.journal_id = journal.journal_id) left outer join url on(paper.id=url.id);")
    
    ids=connections['scholars_db'].cursor().execute("select T1.id as paper_id from paper T1 join (select * from authorof where AUTHOR_ID='" + str(request.session['user_id']) + "') T2 on (T1.id=T2.PAPER_ID);")

    
    
    ids=dictfetchall(ids)
    
    author_list=[]
    for idx,itr in enumerate(ids):
        val=(itr['PAPER_ID'])
        authors=connections['scholars_db'].cursor().execute("select author_id,displayname from author where author_id in(select author_id from authorof"+
        " where paper_id='"+ str(val) +"' );")
        
        authors=dictfetchall(authors)
        author_list.append(authors)

    
    


   
    #cited=dictfetchall(connections['scholars_db'].cursor().execute("select NOTIFICATION from author where author_id='"+ str(request.session['user_id']) +"';")
    
    


    
    context={'papers':dictfetchall(papers),'authors':author_list,'rec_papers':(papers_recommended)}
    
    


    
    return render(request,'general_user/home.html',context=context)
def home(request):

    if 'cited' in request.session:
       del request.session['cited']
    
    if 'loggedIn_admin' in request.session:
            del request.session['loggedIn_admin']

   
 
    papers=connections['scholars_db'].cursor().execute("select distinct T1.id as paper_id,T1.DOI,T1.TITLE,T1.published_year,T1.CITATION,NAME,abstract,publisher,url.id as url_id from paper T1 join  (select * from AUTHOROF) T2 on (T1.id=T2.paper_id) left outer join JOURNAL on (T1.journal_id = journal.journal_id) left outer join url on(T1.id=url.id) order by CITATION desc fetch first 3 rows only;")

    papers_recommended=[]
    if 'loggedIn' in request.session: 
       papers_recommended=dictfetchall(connections['scholars_db'].cursor().execute("select * from (select * from PAPER T1 join(select domain,max(CITATION) as max_cite from paper where DOMAIN in (select NAME from domain where id in (select DOMAIN_ID from EXPERTISE where AUTHOR_ID = '"+ str(request.session['user_id'])   +"')) group by DOMAIN) T2 on (T1.DOMAIN=T2.DOMAIN and T1.CITATION=T2.max_cite)) T1 join (select * from JOURNAL) T2 on (T1.JOURNAL_ID=T2.JOURNAL_ID);"))
       


 

    #ids=connections['scholars_db'].cursor().execute("select paper.id as paper_id from paper join authorof on (paper.id=authorof.author_id) left outer join JOURNAL on (paper.journal_id = journal.journal_id) left outer join url on(paper.id=url.id);")
    
    ids=connections['scholars_db'].cursor().execute("select T1.id as paper_id from paper T1 join (select * from authorof where AUTHOR_ID='" + str(request.session['user_id']) + "') T2 on (T1.id=T2.PAPER_ID);")

    
    
    ids=dictfetchall(ids)
    
    author_list=[]
    for idx,itr in enumerate(ids):
        val=(itr['PAPER_ID'])
        authors=connections['scholars_db'].cursor().execute("select author_id,displayname from author where author_id in(select author_id from authorof"+
        " where paper_id='"+ str(val) +"' );")
        
        authors=dictfetchall(authors)
        author_list.append(authors)

    
    


    
    context={'papers':dictfetchall(papers),'authors':author_list,'rec_papers':(papers_recommended)}
    
    


    
    return render(request,'general_user/home.html',context=context)


def search(request):
  
    if request.method=='POST':
            search=request.POST['search']
     
            c=connections['scholars_db'].cursor()
            c.callproc('get_domains',[str(search)])

            papers=connections['scholars_db'].cursor().execute("select paper.id as paper_id,DOI,TITLE,published_year,CITATION,NAME,abstract,publisher,url.id as url_id from paper join searched on (paper.domain=searched.string) left outer join JOURNAL on (paper.journal_id = journal.journal_id) left outer join url on(paper.id=url.id);")
            ids=connections['scholars_db'].cursor().execute("select paper.id as paper_id from paper join searched on (paper.domain=searched.string) left outer join JOURNAL on (paper.journal_id = journal.journal_id) left outer join url on(paper.id=url.id);")
            ids=dictfetchall(ids)
            author_list=[]
            for idx,itr in enumerate(ids):
                val=(itr['PAPER_ID'])
                authors=connections['scholars_db'].cursor().execute("select author_id,displayname from author where author_id in(select author_id from authorof"+
                " where paper_id='"+ str(val) +"' );")
                
                authors=dictfetchall(authors)
                author_list.append(authors)
            
            
            context={'papers':dictfetchall(papers),'authors':author_list}
            #print(context)
            request.session['searched'] = search
            return render(request,'general_user/paper.html',context=context)


def search_sort(request):
  
    
            search=request.session.get('searched')
     
            c=connections['scholars_db'].cursor()
            c.callproc('get_domains',[str(search)])

            papers=connections['scholars_db'].cursor().execute("select paper.id as paper_id,DOI,TITLE,published_year,CITATION,NAME,abstract,publisher,url.id as url_id from paper join searched on (paper.domain=searched.string) left outer join JOURNAL on (paper.journal_id = journal.journal_id) left outer join url on(paper.id=url.id) order by CITATION desc;")
            ids=connections['scholars_db'].cursor().execute("select paper.id as paper_id from paper join searched on (paper.domain=searched.string) left outer join JOURNAL on (paper.journal_id = journal.journal_id) left outer join url on(paper.id=url.id);")
            ids=dictfetchall(ids)
            author_list=[]
            for idx,itr in enumerate(ids):
                val=(itr['PAPER_ID'])
                authors=connections['scholars_db'].cursor().execute("select author_id,displayname from author where author_id in(select author_id from authorof"+
                " where paper_id='"+ str(val) +"' );")
                
                authors=dictfetchall(authors)
                author_list.append(authors)
            
            
            context={'papers':dictfetchall(papers),'authors':author_list}
            #print(context)
            request.session['searched'] = search
            return render(request,'general_user/paper.html',context=context)
        


                

                
                

            


def author_description(request,author_id):
    
       
       
        affiliation=connections['scholars_db'].cursor().execute("select name from affiliation where id in(select affiliation_id from affiliated_with where  author_id= '" + str(author_id) + "');")
        #papers=connections['scholars_db'].cursor().execute("select id,title from paper E1,(select paper_id from authorof where author_id= '" + str(request.session['user_id']) + "' )E2 where E1.id=E2.paper_id;")
        
        papers_temp=connections['scholars_db'].cursor().execute("select id,title from non_verified_paper E1,(select paper_id from non_verified_authorof where author_id= '" + str(author_id) + "' )E2 where E1.id=E2.paper_id;")
        
        expertise=connections['scholars_db'].cursor().execute("select name from domain where id in(select domain_id from expertise where  author_id= '" + str(author_id) + "');")
        name=connections['scholars_db'].cursor().execute("select displayname from author where  author_id= '" + str(author_id) + "';")
        mail=connections['scholars_db'].cursor().execute("select email from author where  author_id= '" + str(author_id) + "';")
        #cite=connections['scholars_db'].cursor().execute("select displayname from author where author_id ='" + str(request.session['user_id'])+ "';")

        cite=connections['scholars_db'].cursor().execute("select E.author_id,cite_count from(select author.author_id,sum(citation) as cite_count "+
        "from author join authorof on author.author_id = authorof.author_id join PAPER on authorof.paper_id = paper.id group by author.author_id) E "+
        "where author_id ='" + str(author_id)+ "';")

general_user/templates/general_user/authors.html
{% extends "base.html" %}
{% block content %}


    <div class="row">

    
     <div class="col-sm-3 container">
        <div class="card" style="width: 30rem;">
            <img src="https://source.unsplash.com/600x300/?suit" class="card-img-top" alt="..."   width="30" height="100">
            <div class="card-body">
                
              {% for name in name %}
                    <h3 class="card-title">{{name.DISPLAYNAME}}</h3>
              {% endfor %}

              {% for mail in email %}
                    <p><b>Verified Email at:</b> {{mail.EMAIL}}</h3>
              {% endfor %}

              
              {% for cite in citations %}
                    <p><b>Total Citation:</b> {{cite.CITE_COUNT}}</h3>
              {% endfor %}
            
            </div>
            <ul class="list-group list-group-flush">
                {% for versity in affiliation %}
                <li class="list-group-item">{{versity.NAME}}</li>
                {% endfor %}
              
            </ul>
            <div class="card-body">
              {% for domain in expertise %}
                <a href="#" class="card-link">{{domain.NAME}}</a>
              {% endfor %}
            </div>
          </div>
    </div>

    <div class="col-sm-5 container">

      <div class="container">
        <h2>Co Authors</h2>
      </div>
      <style>
          .my-custom-scrollbar {
            position: relative;
            height: 200px;
            overflow: auto;
            }
          .table-wrapper-scroll-y {
          display: block;
          }
      </style>
      <div class="table-wrapper-scroll-y my-custom-scrollbar">

        <table class="table table-bordered table-striped mb-0">
          <thead>
            <tr>
              <th scope="col">Serial</th>
              <th scope="col">Name</th>
              <th scope="col">Email</th>
              
            </tr>
          </thead>
          <tbody>
            {% for author in co_authors %}
            <tr>
              <th scope="row">{{forloop.counter}}</th>
              <td>{{author.DISPLAYNAME}}</td>
              <td>{{author.EMAIL}}</td>
              
              
            </tr>
            {%endfor%}
            
          </tbody>
        </table>
      
      </div>
    </div>

    </div>


    
    
    <br>
    <div class="container">
        <h2 style="margin:0 auto; text-align:left; width:500px;">Accepted Papers</h2>
    </div>
    <br>
    


    <div class="container">
   
      {% load static %}
      {% for paper in papers %}
      {% with idx=forloop.counter %} 
      


      <div class="card  bg-light mb-3"  style="max-width: 70rem;" >

      <div class="row">
        <div class="col-sm-6">
          <div class="card text-black bg-light mb-3">
            <div class="card-body ">
              <h5 class="card-header text-white bg-dark mb-3">{{paper.TITLE}}</h5>
              <h6 class="card-title">Published Year: {{paper.PUBLISHED_YEAR}}</h6>
              <h6 class="card-title">Total Citation: {{paper.CITATION}}</h6>
              <h6 class="card-title">Journal: {{paper.NAME}}</h6>
              <h6 class="card-title">Publisher: {{paper.PUBLISHER}}</h6>
              {% for author in authors %}
                {% with idy=forloop.counter %}
                  {% if idx == idy %}
                  <h5 class="card-title"><u>Authors:</u> </h6>
                    {% for ind in author %}
                      <h6 class="card-title">{{ind.DISPLAYNAME}}</h6>
                    {%endfor%}
                  {%endif%}
                {%endwith%}
              {% endfor %}
            
         
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Abstract</h5>
              <p class="card-text">{{paper.ABSTRACT}}</p>
              {% if paper.URL_ID is not null %}
                <a href="{% url 'general_user:pdf_from_author' pdf_id=paper.URL_ID%}" class="btn btn-primary">Pdf</a>
              {%endif%}
            </div>
          </div>
        </div>
      </div>
      </div>
      
      
      {% endwith %} 
      {% endfor %}
   
      
  </div>
















    <!-- <div class="container">
        <table class="table table-success table-striped table-hover">
            <thead>
              <tr>
                
                <th scope="col">ID</th>
                <th scope="col">Title</th>
                
              </tr>
            </thead>
            <tbody>
            {% for paper in papers %}
            

              <tr>
                <td>{{ paper.ID }}</td>
                <td>{{ paper.TITLE }}</td>
                
              </tr>
              
            {% endfor %}
            </tbody>
          </table>
       
          
    </div> -->


    <div class="container">
      <h2>Non Verified Papers</h2>

    </div>
    <div class="container">
      <table class="table table-success table-striped table-hover">
          <thead>
            <tr>
              
              <th scope="col">ID</th>
              <th scope="col">Title</th>
              
            </tr>
          </thead>
          <tbody>
          {% for paper in papers_temp %}
          

            <tr>
              <td>{{ paper.ID }}</td>
              <td>{{ paper.TITLE }}</td>
              
            </tr>
            
          {% endfor %}
          </tbody>
        </table>
     
        
  </div>
 

{% endblock content %}

general_user/templates/general_user/home.html
{% extends "base.html" %}
{% block content %}

    <div class="py-5 text-center">
      {% load static %} <img class="d-block mx-auto mb-4" src="{% static "images/logo2.jpg" %}" alt="" width="600" height="120">
      <br>
      <h2>Search for Papers</h2>
    </div>

    
    <div class="container">
        <form class="px-md-2" method="POST" action="{% url 'general_user:general_user-search' %}">
            {% csrf_token %}

          <div class="form-outline mb-4">
            <input type="text" id="form3Example1q" class="form-control border" name="search"/>
            <label class="form-label border" for="form3Example1q">
          </div>

         
          


          <br>
       
          <div class="col-md-12 text-center">
            <button type="submit" class="btn btn-success btn-lg mb-1">Find</button>
          </div>

        </form>
    </div>


    <div class="container" >
      <h2 class="text-center my-3 py-3">Top Cited Papers</h2>

      <div class="row">




        {% for paper in  papers%}
        <div class="col-md-4" style="background-color: beige;">
          <div class="col-sm-10">
            <div class="card text-black bg-white mb-3">
              <div class="card-body ">
                <h5 class="card-header text-white bg-dark mb-3">{{paper.TITLE}}</h5>
                <h6 class="card-title"><b>Published Year:</b> {{paper.PUBLISHED_YEAR}}</h6>
                <h6 class="card-title"><b>Total Citation:</b> {{paper.CITATION}}</h6>
                <h6 class="card-title"><b>Journal:</b> {{paper.NAME}}</h6>
                <h6 class="card-title"><b>Publisher:</b> {{paper.PUBLISHER}}</h6>
                {% for author in authors %}
                  {% with idy=forloop.counter %}
                    {% if idx == idy %}
                    <h5 class="card-title"><u>Authors:</u> </h6>
                      {% for ind in author %}
                        <h6 class="card-title">{{ind.DISPLAYNAME}}</h6>
                      {%endfor%}
                    {%endif%}
                  {%endwith%}
                {% endfor %}
              
           
              </div>
            </div>
          </div>
        </div>
        {%endfor%}





      </div>
    </div>

    {% if request.session.loggedIn %}
    <div class="container">
      <h2 class="text-center my-3 py-3">Recommended Articles</h2>

      <div class="row">




        {% for rec_papers in rec_papers%}
        <div class="col-md-4" style="background-color: beige;">
          <div class="col-sm-10">
            <div class="card text-black bg-white mb-3">
              <div class="card-body ">
                <h5 class="card-header text-white bg-info mb-3">{{rec_papers.TITLE}}</h5>
                <h6 class="card-title"><b>Published Year:</b> {{rec_papers.PUBLISHED_YEAR}}</h6>
                <h6 class="card-title"><b>Total Citation:</b> {{rec_papers.CITATION}}</h6>
                <h6 class="card-title"><b>Journal:</b> {{rec_papers.NAME}}</h6>
                <h6 class="card-title"><b>Publisher:</b> {{rec_papers.PUBLISHER}}</h6>
                
              
           
              </div>
            </div>
          </div>
        </div>
        {%endfor%}





      </div>

    </div>
    {%endif%}



    
    
{% endblock content %}

general_user/templates/general_user/paper.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h2>Papers</h2>
</div>
<br>
<div class="container " style="padding-right: 1300px ; width:1000px; ">
      
  <a href="{% url 'general_user:general_user-search_sort' %}" class="btn btn-success" >Sort By Citation</a> 
</div>
<br>
<div class="container">
   
      {% load static %}
      {% for paper in papers %}
      
      {% with idx=forloop.counter %} 
      


      <div class="card  bg-light mb-3"  style="max-width: 70rem;" >

      <div class="row">
        <div class="col-sm-6">
          <div class="card text-black bg-light mb-3">
            <div class="card-body ">
              <h5 class="card-header text-white bg-dark mb-3">{{paper.TITLE}}</h5>
              <h6 class="card-title"> <b>Published Year:</b> {{paper.PUBLISHED_YEAR}}</h6>
              <h6 class="card-title">Total Citation: {{paper.CITATION}}</h6>
              <h6 class="card-title">Journal: {{paper.NAME}}</h6>
              <h6 class="card-title">Publisher: {{paper.PUBLISHER}}</h6>
              {% for author in authors %}
                {% with idy=forloop.counter %}
                  {% if idx == idy %}
                  <br>
                  <h5 class="card-title">Authors: </h6>
                    {% for ind in author %}
                    <a href="{% url 'general_user:author' author_id=ind.AUTHOR_ID%}"><h6 class="card-title">{{ind.DISPLAYNAME}}</h6></a>  
                    
                    {%endfor%}
                  {%endif%}
                {%endwith%}
              {% endfor %}
            
         
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Abstract</h5>
              <p class="card-text">{{paper.ABSTRACT}}</p>
              {% if paper.URL_ID is not null %}
                <a href="{% url 'general_user:pdf' pdf_id=paper.URL_ID%}" class="btn btn-primary">Pdf</a>
              {%endif%}
            </div>
          </div>
        </div>
      </div>
      </div>
      
      
      {% endwith %} 
      {% endfor %}
   
      
</div>
{% endblock content %}