admin_panel/urls.py
from django.urls import path
from admin_panel import views
app_name='admin_panel'
urlpatterns=[
    
    path('admin_panel/',views.login,name='admin_home'),

    path('admin_panel/paper',views.paper,name='admin_paper'),
    path('admin_panel/approve/<int:id>',views.approve,name='approve'),
    path('admin_panel/reject/<int:id>',views.reject,name='reject'),
    
    path('admin_panel/remove/<int:id>',views.delete,name='delete'),

    path('admin_panel/universisty',views.university,name='admin_university'),
    path('admin_panel/universisty/add_university',views.university_new,name='add_university'),

    path('admin_panel/journal',views.journal,name='admin_journal'),
    path('admin_panel/domain/add_journal',views.journal_new,name='add_journal'),

    path('admin_panel/domain',views.domain,name='admin_domain'),
    path('admin_panel/domain/add_domain',views.domain_new,name='add_domain'),

    
    
    
    

]

connect_scholars/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('general_user.urls',namespace="general_user")),
    path('',include('user_info.urls')),
    path('',include('logged_user.urls')),
    path('',include('admin_panel.urls')),

]

general_user/urls.py
from django.urls import path
from general_user import views
app_name='general_user'
urlpatterns=[
    
    path('',views.home_logout,name='home'),
    
    path('home/',views.home,name='general_user-home'),
    #path('home/',views.home_logout,name='home_logout'),
    
    
    path('search/',views.search,name='general_user-search'),
    
    path('search_sorted/',views.search_sort,name='general_user-search_sort'), 
    path('pdf/<int:pdf_id>',views.pdf,name='pdf'),
    path('author_pdf/<int:pdf_id>',views.pdf_from_authors,name='pdf_from_author'),
    path('author/<int:author_id>',views.author_description,name='author'),
    

]

user_info/urls.py
from django.urls import path,include
from user_info import views

app_name='user_info'
urlpatterns = [
    path('login/',views.login,name='Login'),
    path('register/',views.register,name='Register'),

]

admin_panel/models.py
from django.db import models

# Create your models here.

admin_panel/views.py
from http.client import HTTPResponse
from django.shortcuts import render,HttpResponse
from django.db import connection, connections

# Create your views here.

def login(request):
    

    if 'loggedIn_admin' in request.session:
            del request.session['loggedIn_admin']

    if request.method=='POST':
        username_=request.POST['Username']
        password_=request.POST['Password']
    
        if username_=='admin' and password_=='password':
            request.session['loggedIn_admin'] = True
            papers=dictfetchall(connections['scholars_db'].cursor().execute("select * from non_verified_paper;"))
            
            papers_approved=dictfetchall(connections['scholars_db'].cursor().execute("select * from paper;"))
            context={'papers':papers,'approved':papers_approved}
            return render(request,'admin_panel/paper.html',context=context)
        else:
            return render(request,'admin_panel/admin_login.html')
    return render(request,'admin_panel/admin_login.html')


def home(request):
    return render(request,'admin_panel/base.html')

def paper(request):
    if 'loggedIn_admin' in request.session:
        papers=dictfetchall(connections['scholars_db'].cursor().execute("select * from non_verified_paper;"))
        context={'papers':papers}
        
        papers_approved=dictfetchall(connections['scholars_db'].cursor().execute("select * from paper;"))
        context={'papers':papers,'approved':papers_approved}
        return render(request,'admin_panel/paper.html',context=context)
    else:
            return render(request,'admin_panel/admin_login.html')


def delete(request,id):
    connections['scholars_db'].cursor().execute("delete from authorof where paper_id='"+ str(id) +"' ;")
    connections['scholars_db'].cursor().execute("delete from reference where paper_id='"+ str(id) +"' ;")
    
    connections['scholars_db'].cursor().execute("delete from reference where ref_paper_id='"+ str(id) +"' ;")
    
    connections['scholars_db'].cursor().execute("delete from URL where id='"+ str(id) +"' ;")
    connections['scholars_db'].cursor().execute("delete from paper where id='"+ str(id) +"' ;")
    
    connections['scholars_db'].cursor().execute("commit;")
    
    papers=dictfetchall(connections['scholars_db'].cursor().execute("select * from non_verified_paper;"))
    context={'papers':papers}
    
    papers_approved=dictfetchall(connections['scholars_db'].cursor().execute("select * from paper;"))
    context={'papers':papers,'approved':papers_approved}
    return render(request,'admin_panel/paper.html',context=context)


def approve(request,id):
    
    c=dictfetchall(connections['scholars_db'].cursor().execute("select * from non_verified_paper where ID = '"+ str(id) +"';"))[0]
    connections['scholars_db'].cursor().execute("insert into paper(doi,title,published_year,journal_id,abstract,domain,citation) values ('null', '"+ str(c['TITLE']) +"', '"+ str(c['PUBLISED_YEAR']) +"', '"+ str(c['JOURNAL_ID']) +"', '"+ str(c['ABSTRACT']) +"', '"+ str(c['DOMAIN']) +"',0) ;")
    connections['scholars_db'].cursor().execute("commit;")
    new_id=dictfetchall(connections['scholars_db'].cursor().execute("select id from paper where title='"+ str(str(c['TITLE'])) +"';"))[0]['ID']
    
    connections['scholars_db'].cursor().execute("insert into url(ID,LINK) values('"+ str(new_id) +"', '"+ str(c['URL']) +"');")
    connections['scholars_db'].cursor().execute("commit;")
    c=connections['scholars_db'].cursor()
    c.callproc('insert_authorof_references',[str(id),str(new_id)])




    authors=dictfetchall(connections['scholars_db'].cursor().execute("select author_id from non_verified_authorof where paper_id='"+ str(id) +"';"))
    for a in authors:
        for b in authors:
            if a['AUTHOR_ID']!=b['AUTHOR_ID']:
                counts=dictfetchall(connections['scholars_db'].cursor().execute("select * from co_author where author_id='"+ str(a['AUTHOR_ID']) +"' and coauthor_id='"+ str(b['AUTHOR_ID']) +"';"))
                if len(counts)==0:
                    connections['scholars_db'].cursor().execute("insert into co_author(author_id,coauthor_id) values('"+ str(a['AUTHOR_ID']) +"','"+ str(b['AUTHOR_ID']) +"');")
                    connections['scholars_db'].cursor().execute("commit;")
                    connections['scholars_db'].cursor().execute("insert into co_author(author_id,coauthor_id) values('"+ str(b['AUTHOR_ID']) +"','"+ str(a['AUTHOR_ID']) +"');")
                    connections['scholars_db'].cursor().execute("commit;")


    connections['scholars_db'].cursor().execute("delete from non_verified_authorof where paper_id='"+ str(id) +"' ;")
    connections['scholars_db'].cursor().execute("delete from non_verified_reference where paper_id='"+ str(id) +"' ;")
    connections['scholars_db'].cursor().execute("delete from non_verified_paper where id='"+ str(id) +"' ;")
    papers=dictfetchall(connections['scholars_db'].cursor().execute("select * from non_verified_paper;"))

    
    papers_approved=dictfetchall(connections['scholars_db'].cursor().execute("select * from paper;"))
    context={'papers':papers,'approved':papers_approved}
    context={'papers':papers}
    return render(request,'admin_panel/paper.html',context=context)

def reject(request,id):
    c=dictfetchall(connections['scholars_db'].cursor().execute("select * from non_verified_paper where ID = '"+ str(id) +"';"))[0]
    connections['scholars_db'].cursor().execute("delete from non_verified_authorof where paper_id='"+ str(id) +"' ;")
    connections['scholars_db'].cursor().execute("delete from non_verified_reference where paper_id='"+ str(id) +"' ;")
    connections['scholars_db'].cursor().execute("delete from non_verified_paper where id='"+ str(id) +"' ;")
    papers=dictfetchall(connections['scholars_db'].cursor().execute("select * from non_verified_paper;"))
    
    papers_approved=dictfetchall(connections['scholars_db'].cursor().execute("select * from paper;"))
    context={'papers':papers,'approved':papers_approved}
    context={'papers':papers}
    return render(request,'admin_panel/paper.html',context=context)

    

def journal(request):
    if 'loggedIn_admin' in request.session:
        journals=dictfetchall(connections['scholars_db'].cursor().execute("select * from journal;"))
        context={'journals':journals}
        return render(request,'admin_panel/journal.html',context=context)
    else:
        return render(request,'admin_panel/admin_login.html')

def journal_new(request):
    if request.method=='POST':
        title=request.POST['Title']
        publisher=request.POST['Publisher']
        connections['scholars_db'].cursor().execute("insert into JOURNAL(NAME,PUBLISHER) values('"+ str(title) + "','"+ str(publisher) +"');")
        connections['scholars_db'].cursor().execute("commit;")

        journals=dictfetchall(connections['scholars_db'].cursor().execute("select * from journal;"))
        context={'journals':journals}
        return render(request,'admin_panel/journal.html',context=context)
    return render(request,'admin_panel/add_new_journal.html')

def domain(request):
    if 'loggedIn_admin' in request.session:
        domains=dictfetchall(connections['scholars_db'].cursor().execute("select * from domain;"))
        context={'domains':domains}
        return render(request,'admin_panel/domain.html',context=context)

    else:
            return render(request,'admin_panel/admin_login.html')

def domain_new(request):
    if request.method=='POST':
        title=request.POST['Title']
        connections['scholars_db'].cursor().execute("insert into domain(NAME) values('"+ title + "');")
        connections['scholars_db'].cursor().execute("commit;")

        domains=dictfetchall(connections['scholars_db'].cursor().execute("select * from domain;"))
        context={'domains':domains}
        return render(request,'admin_panel/domain.html',context=context)
    return render(request,'admin_panel/add_new_domain.html')

def university(request):
    if 'loggedIn_admin' in request.session:
        university=dictfetchall(connections['scholars_db'].cursor().execute("select * from AFFILIATION;"))
        context={'university':university}
        return render(request,'admin_panel/university.html',context=context)
    
    
    else:
        return render(request,'admin_panel/admin_login.html')

def university_new(request):
    if request.method=='POST':
        name=request.POST['Name']
        webpage=request.POST['Webpage']
        lat=request.POST['Lat']
        lon=request.POST['Long']
        connections['scholars_db'].cursor().execute("insert into affiliation(NAME,WEBPAGE,LATITUDE,LONGITUDE) values('"+ str(name) + "','"+ str(webpage) + "','"+ str(lat) + "','"+ str(lon) + "');")
        connections['scholars_db'].cursor().execute("commit;")

        university=dictfetchall(connections['scholars_db'].cursor().execute("select * from AFFILIATION;"))
        context={'university':university}
        return render(request,'admin_panel/university.html',context=context)
    return render(request,'admin_panel/add_new_university.html')

    
    

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

admin_panel/templates/admin_panel/add_new_domain.html
{% extends "admin_panel/base.html" %}
{% block content %}

<section class="h-100 h-custom" style="background-color: #ffffff;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-8 col-xl-6">
          <div class="card rounded-3">
            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/img3.webp" class="w-100" style="border-top-left-radius: .3rem; border-top-right-radius: .3rem;" alt="Sample photo">
            <div class="card-body p-4 p-md-5">
              <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">Add New Domain</h3>
  
              <form class="px-md-2" method="POST" action="{% url 'admin_panel:add_domain' %}">
                  {% csrf_token %}
  
                <div class="form-outline mb-4">
                    <input type="text" id="form3Example1q" class="form-control" name="Title"/>
                    <label class="form-label" for="form3Example1q">Domain Name</label>
                </div>

                
                <button type="submit" class="btn btn-success btn-lg mb-1">Submit</button>
  
              </form>
  
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

admin_panel/templates/admin_panel/add_new_journal.html
{% extends "admin_panel/base.html" %}
{% block content %}

<section class="h-100 h-custom" style="background-color: #ffffff;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-8 col-xl-6">
          <div class="card rounded-3">
            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/img3.webp" class="w-100" style="border-top-left-radius: .3rem; border-top-right-radius: .3rem;" alt="Sample photo">
            <div class="card-body p-4 p-md-5">
              <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">Add New Journal</h3>
  
              <form class="px-md-2" method="POST" action="{% url 'admin_panel:add_journal' %}">
                  {% csrf_token %}
  
                <div class="form-outline mb-4">
                    <input type="text" id="form3Example1q" class="form-control" name="Title"/>
                    <label class="form-label" for="form3Example1q">Journal Name</label>
                </div>

                <div class="form-outline mb-4">
                    <input type="text" id="form3Example1q" class="form-control" name="Publisher"/>
                    <label class="form-label" for="form3Example1q">Publisher</label>
                </div>

                
                <button type="submit" class="btn btn-success btn-lg mb-1">Submit</button>
  
              </form>
  
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

admin_panel/templates/admin_panel/add_new_university.html
{% extends "admin_panel/base.html" %}
{% block content %}

<section class="h-100 h-custom" style="background-color: #ffffff;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-8 col-xl-6">
          <div class="card rounded-3">
            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/img3.webp" class="w-100" style="border-top-left-radius: .3rem; border-top-right-radius: .3rem;" alt="Sample photo">
            <div class="card-body p-4 p-md-5">
              <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">Add New University</h3>
  
              <form class="px-md-2" method="POST" action="{% url 'admin_panel:add_university' %}">
                  {% csrf_token %}
  
                <div class="form-outline mb-4">
                    <input type="text" id="form3Example1q" class="form-control" name="Name"/>
                    <label class="form-label" for="form3Example1q">University Name</label>
                </div>

                <div class="form-outline mb-4">
                    <input type="text" id="form3Example1q" class="form-control" name="Webpage"/>
                    <label class="form-label" for="form3Example1q">Webpage</label>
                </div>

                <div class="form-outline mb-4">
                    <input type="text" id="form3Example1q" class="form-control" name="Lat"/>
                    <label class="form-label" for="form3Example1q">Latitude</label>
                </div>

                <div class="form-outline mb-4">
                    <input type="text" id="form3Example1q" class="form-control" name="Long"/>
                    <label class="form-label" for="form3Example1q">Longitude</label>
                </div>

                
                <button type="submit" class="btn btn-success btn-lg mb-1">Submit</button>
  
              </form>
  
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

admin_panel/templates/admin_panel/admin_login.html
{% extends "admin_panel/base.html" %}
{% block content %}

<section class="h-100 h-custom" style="background-color: #ffffff;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-8 col-xl-6">
          <div class="card rounded-3">
            {% load static %} <img class="d-block mx-auto mb-4" src="{% static "images/logo2.jpg" %}" alt="" width="600" height="120">
            <div class="container"><h1 style="text-align: center;"> Admin Login</h1></div>
            
            <div class="card-body p-4 p-md-5">
              
              <form class="px-md-2" method="POST" action="{% url 'admin_panel:admin_home' %}">
                  {% csrf_token %}
  
                <div class="form-outline mb-4">
                  <input type="text" id="form3Example1q" class="form-control" name="Username"/>
                  <label class="form-label" for="form3Example1q">Username</label>
                </div>
                
                <div class="form-outline mb-4">
                    <input type="password" id="form3Example1q" class="form-control" name="Password"/>
                    <label class="form-label" for="form3Example1q">Password</label>
                  </div>
  
                <button type="submit" class="btn btn-success btn-lg mb-1">Submit</button>
  
              </form>
  
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

admin_panel/templates/admin_panel/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- CSS only -->
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'general_user:general_user-home' %}"><b>Connect Scholars</b></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              
              
            
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin_panel:admin_paper' %}">Approve Paper</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin_panel:admin_journal' %}">Journal</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin_panel:admin_university' %}">University</a>
              </li>
                
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin_panel:admin_domain' %}">Domain</a>
              </li>
             
              
            </ul>
            
          </div>
        </div>
      </nav>

      
      {% block content %}{% endblock %}
      

</body>
</html>

admin_panel/templates/admin_panel/domain.html
{% extends "admin_panel/base.html" %}
{% block content %}



   



    <div class="container">
       <br>       
      <a href="{% url 'admin_panel:add_domain' %}" class="btn btn-primary">Add New Domain</a> 
    </div>

    <div class="container">
        <table class="table">
            <thead>
              <tr>
                
                <th scope="col">Domain ID</th>
                <th scope="col">Domain Name</th>
              </tr>
            </thead>
            <tbody>

              {% for domain in domains %}
                <tr>
                    <th scope="row">{{domain.ID}}</th>
                    <td>{{domain.NAME}}</td>
                    
                </tr>
              {%endfor%}
              
            </tbody>
          </table>
    </div>

{% endblock content %}

admin_panel/templates/admin_panel/journal.html
{% extends "admin_panel/base.html" %}
{% block content %}



    <div class="container">
        <br>       
        <a href="{% url 'admin_panel:add_journal' %}" class="btn btn-primary">Add New Journal</a> 
    </div>
    <div class="container">
        <table class="table">
            <thead>
              <tr>
                
                <th scope="col">Journal ID</th>
                <th scope="col">Journal Name</th>
                <th scope="col">Publisher</th>
              </tr>
            </thead>
            <tbody>

              {% for journal in journals%}
                <tr>
                    <th scope="row">{{journal.JOURNAL_ID}}</th>
                    <td>{{journal.NAME}}</td>
                    <td>{{journal.PUBLISHER}}</td>
                    
                </tr>
              {%endfor%}
              
            </tbody>
          </table>
    </div>

{% endblock content %}

admin_panel/templates/admin_panel/paper.html
{% extends "admin_panel/base.html" %}
{% block content %}

    <br>
    <br>

    <div class="container">
      <h1> Paper waiting for approval</h1>
      <br>
        <table class="table table-hover">
            <thead>
              <tr>
                
                <th scope="col">Paper ID</th>
                <th scope="col">Paper Title</th>
                <th scope="col">Published Year</th>
                <th scope="col">Journal ID</th>
                <th scope="col">Abstract</th>
                <th scope="col">Domain</th>
                
                <th scope="col">Approval</th>
              </tr>
            </thead>
            <tbody>

              {% for paper in papers %}
                <tr>
                    <th scope="row">{{paper.ID}}</th>
                    <td>{{paper.TITLE}}</td>
                    <td>{{paper.PUBLISED_YEAR}}</td>
                    <td>{{paper.JOURNAL_ID}}</td>
                    <td>{{paper.ABSTRACT}}</td>
                    <td>{{paper.DOMAIN}}</td>
                    <td><a href="{% url 'admin_panel:approve' id=paper.ID%}" class="btn btn-primary">Approve</a></td>
                    <td><a href="{% url 'admin_panel:reject' id=paper.ID%}" class="btn btn-primary">Reject</a></td>
                    
                
                    
                </tr>
              {%endfor%}
              
            </tbody>
          </table>
    </div>

    <br>
    <br>
    <br>
    <div class="container">
      <h1> Paper Approved</h1>
      <br>
        <table class="table table-hover table-success">
            <thead>
              <tr>
                
                <th scope="col">Paper ID</th>
                <th scope="col">Paper Title</th>
                <th scope="col">Published Year</th>
                <th scope="col">Journal ID</th>
                <th scope="col">Abstract</th>
                <th scope="col">Domain</th>
                
                <th scope="col">Remove</th>
              </tr>
            </thead>
            <tbody>

              {% for paper in approved %}
                <tr>
                    <th scope="row">{{paper.ID}}</th>
                    <td>{{paper.TITLE}}</td>
                    <td>{{paper.PUBLISED_YEAR}}</td>
                    <td>{{paper.JOURNAL_ID}}</td>
                    <td>{{paper.ABSTRACT}}</td>
                    <td>{{paper.DOMAIN}}</td>
                    <td><a href="{% url 'admin_panel:delete' id=paper.ID%}" class="btn btn-danger">Remove</a></td>
                    
                
                    
                </tr>
              {%endfor%}
              
            </tbody>
          </table>
    </div>
    


{% endblock content %}

admin_panel/templates/admin_panel/university.html
{% extends "admin_panel/base.html" %}
{% block content %}



    <div class="container">
        <br>       
        <a href="{% url 'admin_panel:add_university' %}" class="btn btn-primary">Add New University</a> 
    </div>
    <div class="container">
        <table class="table">
            <thead>
              <tr>
                
                <th scope="col"> ID</th>
                <th scope="col">University Name</th>
                <th scope="col">Webpage</th>
                <th scope="col">Latitude</th>
                <th scope="col">Longitude</th>
              </tr>
            </thead>
            <tbody>

              {% for uni in university%}
                <tr>
                    <th scope="row">{{uni.ID}}</th>
                    <td>{{uni.NAME}}</td>
                    <td>{{uni.WEBPAGE}}</td>
                    <td>{{uni.LATITUDE}}</td>
                    <td>{{uni.LONGITUDE}}</td>
                    
                </tr>
              {%endfor%}
              
            </tbody>
          </table>
    </div>

{% endblock content %}