connect_scholars/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('general_user.urls',namespace="general_user")),
    path('',include('user_info.urls')),
    path('',include('logged_user.urls')),
    path('',include('admin_panel.urls')),

]

general_user/urls.py
from django.urls import path
from general_user import views
app_name='general_user'
urlpatterns=[
    
    path('',views.home_logout,name='home'),
    
    path('home/',views.home,name='general_user-home'),
    #path('home/',views.home_logout,name='home_logout'),
    
    
    path('search/',views.search,name='general_user-search'),
    
    path('search_sorted/',views.search_sort,name='general_user-search_sort'), 
    path('pdf/<int:pdf_id>',views.pdf,name='pdf'),
    path('author_pdf/<int:pdf_id>',views.pdf_from_authors,name='pdf_from_author'),
    path('author/<int:author_id>',views.author_description,name='author'),
    

]

logged_user/urls.py
from django.urls import path
from logged_user import views
app_name='logged_user'
urlpatterns=[
    
    path('logged_user/',views.logged_user,name='logged_user-home'),
    path('add_paper/',views.add_paper,name="add_paper"),
    

]

user_info/urls.py
from django.urls import path,include
from user_info import views

app_name='user_info'
urlpatterns = [
    path('login/',views.login,name='Login'),
    path('register/',views.register,name='Register'),

]

logged_user/models.py
from django.db import models

# Create your models here.

logged_user/views.py
from django.shortcuts import redirect, render,HttpResponse
from django.db import connection, connections
from django.shortcuts import reverse
import re

from tkinter import Tk
from tkinter import filedialog
import os
# Create your views here.



    

def add_paper(request):
    if 'loggedIn' in request.session and request.session['loggedIn'] == True:
         if request.method=='POST':
            title=request.POST['Title']
            journal=request.POST['Journal']
            date=request.POST['Date']
            domain=request.POST['Domain']
            abstract=request.POST['Abstract']
            authors=request.POST['Authors']
            references=request.POST['References']
            url=request.POST['url']


            

            
            

            if(title=='' or journal=='' or date=='' or domain=='' or abstract=='' or authors=='' or references=='' or url==''):
               context={'error':'Please fill all fields'}
               return render(request,'error.html',context=context) 


            
            c=dictfetchall(connections['scholars_db'].cursor().execute("select * from journal where NAME= '"+ str(journal) +"';"))
            if(len(c)==0):
                context={'error':'Journal Name not found'}
                return render(request,'error.html',context=context)
            
            c=dictfetchall(connections['scholars_db'].cursor().execute("select * from domain where NAME= '"+ str(domain) +"';"))
            if(len(c)==0):
                context={'error':'Domain Name not found'}
                return render(request,'error.html',context=context)
            
            regex=r'[0-9]{4}'
            if not re.fullmatch(regex, date):
                context={'error':'Date format invalid'}
                return render(request,'error.html',context=context)
            
            


            journal_id=dictfetchall(connections['scholars_db'].cursor().execute("select JOURNAL_ID from journal where name= '"+ str(journal) + "';"))[0]['JOURNAL_ID']
            
            url=str('E:\\2-2\DataBase_Lab\Project\django\connect_scholars\pdfs\\')+str(url)

            connections['scholars_db'].cursor().execute("insert into non_verified_paper(title,publised_year,journal_id,domain,ABSTRACT,url) "+
                 "values ('" + str(title) + "','" + str(date) + "','" + str(journal_id) + "','"+ str(domain) +"','"+ str(abstract) +"','"+ str(url) +"' )  ;")
            
            
            
            
            
            connections['scholars_db'].cursor().execute("commit;")


            author_ids=[]
            ref_ids=[]
            authors=authors.split(';')
            references=references.split(';')
            
            for author in authors:
                flag=0
                with connections['scholars_db'].cursor() as c:
                    for row in c.execute("SELECT AUTHOR_ID FROM AUTHOR WHERE USERNAME='" + str(author) + "'"):
                        flag=1
                        id=row[0]

                if(flag==0):
                    context={'error':'Invalid Author Names'}
                    return render(request,'error.html',context=context)     
                author_ids.append(id)
            if(request.session['user_id'] not in author_ids):
                author_ids.append(request.session['user_id'])
            


            
            for paper in references:
                flag=0
                with connections['scholars_db'].cursor() as c:
                    for row in c.execute("SELECT ID FROM PAPER WHERE TITLE='" + str(paper) + "'"):
                        flag=1
                        id=row[0]

                if(flag==0):
                    context={'error':'Referenced Papers not found'}
                    return render(request,'error.html',context=context)       
                ref_ids.append(id)

            
                               
            paper_id=dictfetchall(connections['scholars_db'].cursor().execute("select id from non_verified_paper where title= '"+ str(title) +"' "))[0]['ID']



            for id in ref_ids: 
                connections['scholars_db'].cursor().execute("insert into non_verified_reference(paper_id,ref_paper_id)values "+
                "( '"+ str(paper_id) +"', '"+ str(id) +"'  )")
                connections['scholars_db'].cursor().execute("commit;")




            for id_ in author_ids:
                connections['scholars_db'].cursor().execute("insert into non_verified_authorof(author_id,paper_id)values "+
                "( '"+ str(id_) +"', '"+ str(paper_id) +"'  )")
                connections['scholars_db'].cursor().execute("commit;")
            
            
            



            return redirect(reverse('general_user:general_user-home'))

           
        
         return render(request,'logged_user/add_paper.html')
    
    else:
        redirect(request,'general_user/general_user-home')

def logged_user(request):
    
    if 'loggedIn' in request.session and request.session['loggedIn'] == True:
        if 'cited' in request.session:
            del request.session['cited']
        
        affiliation=connections['scholars_db'].cursor().execute("select name from affiliation where id in(select affiliation_id from affiliated_with where  author_id= '" + str(request.session['user_id']) + "');")
        #papers=connections['scholars_db'].cursor().execute("select id,title from paper E1,(select paper_id from authorof where author_id= '" + str(request.session['user_id']) + "' )E2 where E1.id=E2.paper_id;")
        
        papers_temp=connections['scholars_db'].cursor().execute("select id,title from non_verified_paper E1,(select paper_id from non_verified_authorof where author_id= '" + str(request.session['user_id']) + "' )E2 where E1.id=E2.paper_id;")
        
        expertise=connections['scholars_db'].cursor().execute("select name from domain where id in(select domain_id from expertise where  author_id= '" + str(request.session['user_id']) + "');")
        name=connections['scholars_db'].cursor().execute("select displayname from author where  author_id= '" + str(request.session['user_id']) + "';")
        mail=connections['scholars_db'].cursor().execute("select email from author where  author_id= '" + str(request.session['user_id']) + "';")
        #cite=connections['scholars_db'].cursor().execute("select displayname from author where author_id ='" + str(request.session['user_id'])+ "';")

        cite=connections['scholars_db'].cursor().execute("select E.author_id,cite_count from(select author.author_id,sum(citation) as cite_count "+
        "from author join authorof on author.author_id = authorof.author_id join PAPER on authorof.paper_id = paper.id group by author.author_id) E "+
        "where author_id ='" + str(request.session['user_id'])+ "';")


        papers=connections['scholars_db'].cursor().execute("select T1.id as paper_id,T1.DOI,T1.TITLE,T1.published_year,T1.CITATION,NAME,abstract,publisher,url.id as url_id from paper T1 join  (select * from AUTHOROF where AUTHOR_ID='" + str(request.session['user_id']) + "') T2 on (T1.id=T2.paper_id) left outer join JOURNAL on (T1.journal_id = journal.journal_id) left outer join url on(T1.id=url.id);")
       

        #ids=connections['scholars_db'].cursor().execute("select paper.id as paper_id from paper join authorof on (paper.id=authorof.author_id) left outer join JOURNAL on (paper.journal_id = journal.journal_id) left outer join url on(paper.id=url.id);")
        
        ids=connections['scholars_db'].cursor().execute("select T1.id as paper_id from paper T1 join (select * from authorof where AUTHOR_ID='" + str(request.session['user_id']) + "') T2 on (T1.id=T2.PAPER_ID);")

        
        
        ids=dictfetchall(ids)
       
        author_list=[]
        for idx,itr in enumerate(ids):
            val=(itr['PAPER_ID'])
            authors=connections['scholars_db'].cursor().execute("select author_id,displayname from author where author_id in(select author_id from authorof"+
            " where paper_id='"+ str(val) +"' );")
            
            authors=dictfetchall(authors)
            author_list.append(authors)

        cited=dictfetchall (connections['scholars_db'].cursor().execute("select NOTIFICATION from author where author_id='"+ str(request.session['user_id']) +"';"))[0]['NOTIFICATION']
      
        if cited=='true':
            request.session['cited'] = True
        
        connections['scholars_db'].cursor().execute("update author set NOTIFICATION='"+ str('false') +"' where author_id='"+ str(request.session['user_id']) +"';")
        connections['scholars_db'].cursor().execute("commit;")
        


        co_authors=dictfetchall(connections['scholars_db'].cursor().execute("select DISPLAYNAME,EMAIL from AUTHOR T1 join (select COAUTHOR_ID from CO_AUTHOR where author_id='"+ str(request.session['user_id']) +"') T2 on (T1.AUTHOR_ID=T2.COAUTHOR_ID);"))

        #cited=dictfetchall(connections['scholars_db'].cursor().execute("select NOTIFICATION from author where author_id='"+ str(request.session['user_id']) +"';")
        
        context={'name':dictfetchall(name),'papers':dictfetchall(papers),'authors':author_list,'papers_temp':dictfetchall(papers_temp),'affiliation':dictfetchall(affiliation),'expertise':dictfetchall(expertise),'email':dictfetchall(mail),'citations': dictfetchall(cite),'co_authors':co_authors}
        #context={'affiliation':dictfetchall(affiliation)}
        
        
        
        return render(request,'logged_user/dashboard.html',context=context)
    else:
        redirect(request,'general_user/general_user-home')




def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

logged_user/templates/logged_user/add_paper.html
{% extends "base.html" %}
{% block content %}

  <div class="container">
  <section class="h-100 h-custom" >
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-8 col-xl-6">
          <div class="card rounded-3">
            {% load static %} <img class="d-block mx-auto mb-4" src="{% static "images/logo2.jpg" %}" alt="" width="600" height="120">
            <div class="card-body p-4 p-md-5">
              <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">Add Paper</h3>
  
              <form class="px-md-2" method="POST" action="{% url 'logged_user:add_paper' %}">
                  {% csrf_token %}
  
                <div class="form-outline mb-4">
                  <input type="text" id="form3Example1q" class="form-control" name="Title"/>
                  <label class="form-label" for="form3Example1q">Title</label>
                </div>

                <div class="form-outline mb-4">
                    <input type="text" id="form3Example1q" class="form-control" name="Journal"/>
                    <label class="form-label" for="form3Example1q">Journal</label>
                </div>

                <div class="form-outline mb-4">
                    <input type="text" id="form3Example1q" class="form-control" name="Date"/>
                    <label class="form-label" for="form3Example1q">Date</label>
                </div>

                <div class="form-outline mb-4">
                    <input type="text" id="form3Example1q" class="form-control" name="Domain"/>
                    <label class="form-label" for="form3Example1q">Domain</label>
                </div>
                <div class="form-outline mb-4">
                    <input type="text" id="form3Example1q" class="form-control" name="Abstract"/>
                    <label class="form-label" for="form3Example1q">Abstract</label>
                </div>

                <div class="form-outline mb-4">
                  <input type="text" id="form3Example1q" class="form-control" name="Authors"/>
                  <label class="form-label" for="form3Example1q">Authors</label>
                  <!-- <textarea rows="4" cols="50" name="Authors" form="usrform">
                   Type Author Names with ';'</textarea> -->
                </div>

                <div class="form-outline mb-4">
                  <input type="text" id="form3Example1q" class="form-control" name="References"/>
                  <label class="form-label" for="form3Example1q">Cited Papers</label>
                  <!-- <textarea rows="4" cols="50" name="Authors" form="usrform">
                   Type Author Names with ';'</textarea> -->
                </div>

                <div class="form-outline mb-4">
                  <input type="file" id="form3Example1q" class="form-control" name="url"/>
                  <label class="form-label" for="form3Example1q">Add PDF</label>
                  <!-- <textarea rows="4" cols="50" name="Authors" form="usrform">
                   Type Author Names with ';'</textarea> -->
                </div>
               



                

                
  
                <button type="submit" class="btn btn-success btn-lg mb-1">Submit</button>
  
              </form>
  
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  </div>

{% endblock content %}

logged_user/templates/logged_user/dashboard.html
{% extends "base.html" %}
{% block content %}


    <div class="row">

    
     <div class="col-sm-3 container">
        <div class="card" style="width: 30rem;">
            <img src="https://source.unsplash.com/600x300/?scientist" class="card-img-top" alt="..."   width="30" height="100">
            <div class="card-body">
                
              {% for name in name %}
                    <h3 class="card-title">{{name.DISPLAYNAME}}</h3>
              {% endfor %}

              {% for mail in email %}
                    <p><b>Verified Email at:</b> {{mail.EMAIL}}</h3>
              {% endfor %}

              
              {% for cite in citations %}
                    <p><b>Total Citation:</b> {{cite.CITE_COUNT}}</h3>
              {% endfor %}
            
            </div>
            <ul class="list-group list-group-flush">
                {% for versity in affiliation %}
                <li class="list-group-item">{{versity.NAME}}</li>
                {% endfor %}
              
            </ul>
            <div class="card-body">
              {% for domain in expertise %}
                <a href="#" class="card-link">{{domain.NAME}}</a>
              {% endfor %}
            </div>
          </div>
    </div>

    <div class="col-sm-5 container">

      <div class="container">
        <h2>Co Authors</h2>
      </div>
      <style>
          .my-custom-scrollbar {
            position: relative;
            height: 200px;
            overflow: auto;
            }
          .table-wrapper-scroll-y {
          display: block;
          }
      </style>
      <div class="table-wrapper-scroll-y my-custom-scrollbar">

        <table class="table table-bordered table-striped mb-0">
          <thead>
            <tr>
              <th scope="col">Serial</th>
              <th scope="col">Name</th>
              <th scope="col">Email</th>
              
            </tr>
          </thead>
          <tbody>
            {% for author in co_authors %}
            <tr>
              <th scope="row">{{forloop.counter}}</th>
              <td>{{author.DISPLAYNAME}}</td>
              <td>{{author.EMAIL}}</td>
              
              
            </tr>
            {%endfor%}
            
          </tbody>
        </table>
      
      </div>
    </div>

    </div>


    
    
    <br>
    <div class="container">
        <h2 style="margin:0 auto; text-align:left; width:500px;">Accepted Papers</h2>
    </div>
    <br>
    <div class="container " style="padding-left: 50px ; width:500px;">
      
      <a href="{% url 'logged_user:add_paper' %}" class="btn btn-success" >Add New Paper</a> 
    </div>
    <br>


    <div class="container">
   
      {% load static %}
      {% for paper in papers %}
      {% with idx=forloop.counter %} 
      


      <div class="card  bg-light mb-3"  style="max-width: 70rem;" >

      <div class="row">
        <div class="col-sm-6">
          <div class="card text-black bg-light mb-3">
            <div class="card-body ">
              <h5 class="card-header text-white bg-dark mb-3">{{paper.TITLE}}</h5>
              <h6 class="card-title">Published Year: {{paper.PUBLISHED_YEAR}}</h6>
              <h6 class="card-title">Total Citation: {{paper.CITATION}}</h6>
              <h6 class="card-title">Journal: {{paper.NAME}}</h6>
              <h6 class="card-title">Publisher: {{paper.PUBLISHER}}</h6>
              {% for author in authors %}
                {% with idy=forloop.counter %}
                  {% if idx == idy %}
                  <h5 class="card-title"><u>Authors:</u> </h6>
                    {% for ind in author %}
                    <a href="{% url 'general_user:author' author_id=ind.AUTHOR_ID%}"><h6 class="card-title">{{ind.DISPLAYNAME}}</h6></a>  
                    {%endfor%}
                  {%endif%}
                {%endwith%}
              {% endfor %}
              
         
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Abstract</h5>
              <p class="card-text">{{paper.ABSTRACT}}</p>
              {% if paper.URL_ID is not null %}
                <a href="{% url 'general_user:pdf' pdf_id=paper.URL_ID%}" class="btn btn-primary">Pdf</a>
              {%endif%}
            </div>
          </div>
        </div>
      </div>
      </div>
      
      
      {% endwith %} 
      {% endfor %}
   
      
  </div>
















    <!-- <div class="container">
        <table class="table table-success table-striped table-hover">
            <thead>
              <tr>
                
                <th scope="col">ID</th>
                <th scope="col">Title</th>
                
              </tr>
            </thead>
            <tbody>
            {% for paper in papers %}
            

              <tr>
                <td>{{ paper.ID }}</td>
                <td>{{ paper.TITLE }}</td>
                
              </tr>
              
            {% endfor %}
            </tbody>
          </table>
       
          
    </div> -->


    <div class="container">
      <h2>Non Verified Papers</h2>

    </div>
    <div class="container">
      <table class="table table-success table-striped table-hover">
          <thead>
            <tr>
              
              <th scope="col">ID</th>
              <th scope="col">Title</th>
              
            </tr>
          </thead>
          <tbody>
          {% for paper in papers_temp %}
          

            <tr>
              <td>{{ paper.ID }}</td>
              <td>{{ paper.TITLE }}</td>
              
            </tr>
            
          {% endfor %}
          </tbody>
        </table>
     
        
  </div>
 

{% endblock content %}