connect_scholars/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('general_user.urls',namespace="general_user")),
    path('',include('user_info.urls')),
    path('',include('logged_user.urls')),
    path('',include('admin_panel.urls')),

]

general_user/urls.py
from django.urls import path
from general_user import views
app_name='general_user'
urlpatterns=[
    
    path('',views.home_logout,name='home'),
    
    path('home/',views.home,name='general_user-home'),
    #path('home/',views.home_logout,name='home_logout'),
    
    
    path('search/',views.search,name='general_user-search'),
    
    path('search_sorted/',views.search_sort,name='general_user-search_sort'), 
    path('pdf/<int:pdf_id>',views.pdf,name='pdf'),
    path('author_pdf/<int:pdf_id>',views.pdf_from_authors,name='pdf_from_author'),
    path('author/<int:author_id>',views.author_description,name='author'),
    

]

logged_user/urls.py
from django.urls import path
from logged_user import views
app_name='logged_user'
urlpatterns=[
    
    path('logged_user/',views.logged_user,name='logged_user-home'),
    path('add_paper/',views.add_paper,name="add_paper"),
    

]

user_info/urls.py
from django.urls import path,include
from user_info import views

app_name='user_info'
urlpatterns = [
    path('login/',views.login,name='Login'),
    path('register/',views.register,name='Register'),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- CSS only -->
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'general_user:general_user-home' %}"><b>Connect Scholars</b></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              
              
              {% load static %}

              {% if not request.session.loggedIn %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'user_info:Login' %}">My Profile</a>
              </li>
               
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logged_user:logged_user-home' %}">My Profile</a>
              </li>
                
              {% endif %}
              
            </ul>
            
          </div>
        </div>
      </nav>
      

      <!-- <a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
        More
      </a> -->
      <button class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample" type="button" style="background: rgb(255, 255, 255);color: rgb(0,0,0);border-width: 2px;border-color: rgb(255, 255, 255);border-radius: 11px;"><i class="fa fa-list"></i></button>
     
      
      <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
        <div class="offcanvas-header">
          <!-- <h5 class="offcanvas-title" id="offcanvasExampleLabel">Connect Scholars</h5> -->
          
            {% load static %} <img class="d-block mx-auto mb-4" src="{% static "images/logo2.jpg" %}" alt="" width="300" height="60">
            
            
         
      
          <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">

          <div class="h4" style="background-color:rgb(14, 77, 56) ;color:rgb(255, 255, 255);text-align: center;">Notification Corner</div>
          {% if not request.session.loggedIn %}
          <div class="h6" style="background-color: rgb(247, 207, 193);text-align: center;">Login to see your Notifications!</div>
          {% else %}
            {%if not request.session.cited%}
              <div class="h6" style="background-color: rgb(247, 207, 193);text-align: center;">No Notification</div>
            {% else %}
              <div class="h6" style="background-color: rgb(187, 240, 151);text-align: center;">You Are Recently Cited</div>
            {%endif%}
          {% endif %}
          
         
          
        </br>
        <div class="d-grid gap-2">
          {% load static %}

          {% if not request.session.loggedIn %}
         
          
          <a href="{% url 'user_info:Login' %}" class="btn btn-success">My Profile</a> 
          {%else%}
          
          <a href="{% url 'logged_user:logged_user-home' %}" class="btn btn-success">My Profile</a> 
          {%endif%}
          
        </div>
        <hr>


            
            
          
          <br>

          
          <br>
          
          <div class="d-grid gap-2">
            {% load static %}

            {% if not request.session.loggedIn %}
              
              <a href="{% url 'user_info:Login' %}" class="btn btn-primary">Log In</a> 
            {% else %}
              <a href="{% url 'general_user:home' %}" class="btn btn-primary">Sign Out</a> 
            {% endif %}
            
          </div>
          <br>
          <div class="d-grid gap-2">
            {% if not request.session.loggedIn %}
              <a href="{% url 'user_info:Register' %}" class="btn btn-primary">Sign Up</a> 
            {% endif %}
          </div>

          <hr>
          <br>
          <br>
          <br>
          <br>
          <br>

          <br>
          <br>
          <h3 style="text-align: center;">Developed By</h3>
          <br>

          <div class="row">
            <div class="col-sm-6">
              <div class="card" style="width: 10rem;">
                <img src="{% static "images/toki.PNG" %}" class="card-img-top" alt="..."  width="100" height="150">
                <div class="card-body">
                  <h5 class="card-title" style="font-size: 16px;">Md Toki Tahmid</h5>
                  <h5 class="card-title" style="font-size: 16px;">ID: 1805030</h5>
                  
                </div>
              </div>


            </div>

            <div class="col-sm-6">
              <div class="card" style="width: 10rem;">
                <img src="{% static "images/nafis.PNG" %}" class="card-img-top" alt="..." width="100" height="150">
                <div class="card-body">
                  <h5 class="card-title" style="font-size: 16px;">Nafis Karim</h5>
                  <h5 class="card-title" style="font-size: 16px;">ID: 1805027</h5>
                  
                </div>
              </div>


            </div>

          </div>
         
          </div>
          
          
        </div>
      

    </hr>
      {% block content %}{% endblock %}
    
</body>
</html>

templates/error.html
<!DOCTYPE html>
<html lang="en" >
    <head>
        <meta charset="UTF-8">
        <title>{{error}}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.min.css" />
        <style>
            html, body{
            height: 100%;
            font-size: 62.5%;
            font-family: Verdana, sans-serif;
            }
            .container {
            position: relative;
            height: 100%;
            width: 100%;
            }
            .inner {
            position: absolute;
            max-width: 960px;
            top: 30%;
            left: 20%;
            right: 0;
            
            font-size: 30px;
            font-weight: 400;
            }
            .grid {
            display: flex; 
			flex-wrap: wrap; 
            justify-content: center; 
            align-items: center; 
            }
            .cell { 
            box-sizing: border-box; 
            flex-shrink: 0; 
            width: calc(100% * 5 / 12); 
            }
            img {
            height: 100%; 
            width: 100%; 
            }
            @media only screen and (max-width:600px) {
			.inner {
			left: 10%;
			}
            .cell {
            width: 100%;
            }
			img {
			padding-top: 50px;
            }
            }
        </style>
    </head>
    <body>
        
		<div class="container">
            
            <div class="inner">
                <div class="grid">
                    <div class="cell" id="write"></div>
                    <div class="cell"><img src="https://i.imgur.com/tMJkbbq.png" /></div>
                </div>
            </div>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/typeit/5.10.6/typeit.min.js"></script>
        <script>
            new TypeIt('#write', {
            strings: ["{{error}}"],
            speed: 50,
            autoStart: false
            });
        </script>
    </body>
</html>